### PR TITLE
Echo service

### PR DESCRIPTION
**Pull request by wtrocki**
Implementation for idea presented in https://github.com/julien-lafont/Mocky/issues/33
Raw version.
It may require some final touches.

### CODE REVIEW

**Comment by wtrocki** [comment]
@julien-lafont I could not figure out easy way to pipe any type of payload. This will support only JSON payload. Need to add some error handling if you think that this feature is useful. I have been using and recommending mocky for long time. Echo option is the most wanted feature to make it perfect tool.

**Comment by szeco** [comment]
@wtrocki - any way to expand on the echo option so that it replays the request headers as well as the body? or an option to choose which is echo'd?

**Comment by wtrocki** [comment]
Added headers that were specified by user.

**Comment by wtrocki** [comment]
Closing

**Pull request closed without merging**
